# Auto generated by pluginv ensure_setup_py task
from setuptools import find_packages, setup

setup(
    name="Sample_Gateway_Auth_Plugin_For_Shared_Sessions".lower(),
    version="1.0",
    packages=find_packages(exclude=["*.tests", "*.tests.*", "tests.*", "tests"]),
    py_modules=["main"],
)
